### ISSUE TITLE
Add support for Actions environment files

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/gidgethub#132]
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
https://github.com/actions/toolkit/blob/main/packages/core/src/file-command.ts

**Comment by dhruvmanila** [comment]
I can implement this :)

Also, according to [this blog post](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/), both `set-env` and `add-path` commands are going to be removed on November 16 which means we should probably remove the following two tests as well:
- https://github.com/brettcannon/gidgethub/blob/master/tests/test_actions.py#L64
- https://github.com/brettcannon/gidgethub/blob/master/tests/test_actions.py#L72 

Should we aim for this feature in `v5.0.0`?

**Comment by brettcannon** [comment]
@dhruvmanila thanks for being willing to give it a shot!

You're right, those tests could be removed.

As for implementing, do look at how actions/core does it in JavaScript (we already have their MIT license covered so you can copy the algorithm as appropriate).

**Comment by brettcannon** [comment]
And we can make this part of a 5.0 release.

**Comment by dhruvmanila** [comment]
Awesome! I took a look at how actions/core are doing it and there's one additional thing they are implementing in their API. 

> The action that creates or updates the environment variable does not have access to the new value, but all subsequent actions in a job will have access. 

According to GitHub, the current action cannot access the new environment variable or the modified path but only the subsequent actions can. 

The actions/core library is adding the environment variable and path to their respective file but additionally, they are manually injecting them so that even the current action can access them. Should we also implement this?

https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L43
https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L74

**Comment by brettcannon** [comment]
> The actions/core library is adding the environment variable and path to their respective file but additionally, they are manually injecting them so that even the current action can access them. Should we also implement this?

Yes, I think we should.

> Also, you have mentioned in here that we are not performing any string conversion, should we change that as I think it just requires casting the parameter to str or am I wrong

You're correct that's all it would take, but I don't want to change that as debugging passing in an object like that is really hard since every object can be converted to a string.
