### ISSUE TITLE
Integration Authentication

### ISSUE THREAD

**Issue by dstufft** [brettcannon/gidgethub#23]
Github integrations is a way to write a bot that doesn't require an actual user, however it uses a different authentication mechanism. You can see more details at https://developer.github.com/early-access/integrations/authentication/. This is a bit tricky because certain URLs require a different kind of authentication than other URLs.

Perhaps allowing authorization headers to be passed in like accept headers would be useful here?

**Comment by brettcannon** [comment]
Maybe there should be a `token` argument and a `auth_type` argument? E.g. `auth_type="token", auth_token="oauth_token"` and so you can just swap out as necessary for integration versus installation authentication. Otherwise there should be an `auth` argument that takes a two-item iterable, e.g. `("token", "oauth_token")`, but that seems unnecessarily verbose for the common case.

I also don't know if it makes sense to have overridable auth details in every method in `GitHubAPI`. Is the need to use different types of auth that common? And is it that expensive to create a new instance of `GitHubAPI` for different auth scenarios? Just some stuff to think about.

**Comment by Mariatta** [comment]
I think `auth_type` argument makes sense, but then we should rename `oauth_token` to just `token` (backwards incompatible).

Something like:
```
def create_headers(requester: str, *, accept: str = accept_format(),
                   auth_type: Optional[str] = "token",
                   token: Optional[str] = None,
                   )
       # auth_type should be in ['token', 'bearer']
       # token: means authenticating using Personal access token (OAuth token)
      # bearer: authenticating as a GitHub App (json web token)
      headers["authorization"] = f"{auth_type} {oauth_token}"
```

I guess it can also be kept as `oauth_token`, but it seems incorrect :)

Thoughts?

**Comment by merwok** [comment]
I tend to dislike magic strings (i.e. it’s a switch, not an arbitrary string).
What about having two exclusive parameters?  (both have default None, exception raised if both are None or both are given e.g. `if [user_token, app_token].count(None) != 1`)

**Comment by Mariatta** [comment]
At the moment it is just a switch of two types of GitHub authentications.
But maybe we want to make it flexible for future auth types? 🤷‍♀️ 

Edit: `auth_type` can be an enum.

For comparison, gitlab's auth types are "Bearer" and "Private-token".

**Comment by brettcannon** [comment]
Why not have a `jwt` argument next to `auth_token`? That way you just set one of them instead of having to set two arguments and the semantic meaning of `token` be based on `auth_type`?

**Comment by merwok** [comment]
That’s what I tried to say :)
