### ISSUE TITLE
Idea for gidgethub apps (similar to Django apps)

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#67]
I'm actually not sure if this is the right place to discuss this.

Looking at each of the aiohttp + gidgethub webservices that I'm familiar with ([the-knights-who-say-ni](https://github.com/python/the-knights-who-say-ni), [bedevere](https://github.com/python/bedevere), [miss-islington](https://github.com/python/miss-islington), [black-out](https://github.com/Mariatta/black_out), etc), I've been thinking that perhaps it would be great for each of them to exist as a library, and pip installable.

So I could create only one webservice that can be an aiohttp webserver (or others that are supported by gidgethub), and somehow just be able to include bedevere or black_out as "installed_apps" (like the way django has [INSTALLED_APPS](https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-INSTALLED_APPS)).

I'm sure this is already possible right now, but perhaps I haven't architectured my gidgethub projects correctly, and not sure how yet.

**Comment by brettcannon** [comment]
I've been thinking about this and I think anything you and I have used in two or more bots should probably end up in a`gidgethub.utils` subpackage with a clear messaging that forward-compatibility is best-effort as chances are anything we put in that sub-package could break if GitHub changed something.

After that is the question on how to structure things. E.g. do we assume labels are specified as enums? Should we provider routers for each module so this is truly drop-in for anyone who wants to use something?

**Comment by webknjaz** [comment]
@Mariatta @brettcannon FYI I'm building a framework which is kinda related to the topic of this issue. But takes a bit different approach for now.

Elevator pitch: it should allow end-users to write GitHub Apps starting using interface as easy as
```python
from octomachinery.app import RUNTIME_CONTEXT, run as run_app
from octomachinery.github import events


@events.integration_installation.handler
async def on_install(action, installation, sender, repositories=None):
    github_client = RUNTIME_CONTEXT.github_installation  # contextvars proxy
    await github_client.get_sender_info()
    # ...


__name__ == '__main__' and run_app()
```
hiding copy-paste and it's going to mirror a lot of features from probot.

Landing: https://octomachinery.dev/
PoC usage example: https://github.com/sanitizers/chronographer-github-app/blob/8fdd095/chronographer/event_handlers.py#L69-L182

Built on top of:
* low-level APIs of aiohttp.web server
* gidgethub
* attrs-based models

Going to release a very early alpha preview soon :)

**Comment by brettcannon** [comment]
Another potential point of inspiration: https://danger.systems/js/

**Comment by njsmith** [comment]
I also ended up writing a bit of a framework for GH apps: https://github.com/python-trio/snekomatic/blob/master/snekomatic/gh.py

For now I've just been hacking on it as part of my bot. I'm not at all sure what its final form should be (my personal hacks? standalone library? part of gidgethub?), but the core is pretty usable already and has a decent test suite. (Though better testing tools is definitely something else I'd like to see factored out into shared libraries.)

I haven't been thinking as much about `pip install`able plugins – though that's a cool idea! But even just with my little bot, I'm wondering about the best way to modularize it internally, and don't have a great solution yet.

The way bedevere does it with `gidgethub.sansio.Router` objects is a great start. I was kind of hoping to not expose gidgethub internals if I can help it though, just because there are already **a lot** of moving pieces you have to keep track of when building a gh app and gidgethub (appropriately) exposes a lot of details at different abstraction levels, so it seemed like if we could hide gidgethub behind a solid abstraction that would be nice? Also `Router` doesn't expose any way to add a sub-`Router` after creation, which I found awkward, since if you start with one `Router` and then add a sub-module with its own `Router`, have you're forced to refactor your original `Router` into a submodule as well and add a third root `Router`. Anyway, what I've ended up with for now is..... my own implementation of `gidgethub.sansio.Router` with zero added features. Which is silly.

Flask blueprints might be another inspiration (I guess they're very similar to gidgethub's `Router`): https://flask.palletsprojects.com/en/1.1.x/blueprints/

Some other things that larger apps might want to think about:

- Each sub-app will have its own set of requirements for permissions and webhook subscriptions. It would be nice if there was an easy way to collect these up and tell the users "here's the complete set you need". Or even "here's the diff between what you currently have configured on Github, and what you actually need". You could also imagine giving sub-apps tokens with restricted permissions based on what they declared they need, so they can't accidentally do things they shouldn't...

- For some of the vague ideas I have in mind, it would make sense for the bot to have an actual web interface. (For example, here's the dashboard for a github bot that rust uses: https://buildbot2.rust-lang.org/homu/queue/rust). In anticipation of this, `snekomatic/gh.py` is designed to integrate into a larger web app framework (right now I'm using [quart](https://pypi.org/project/Quart/), which is basically flask for asyncio+trio). If sub-apps each want to provide their own web interface, then we'll need some way to integrate those too.

This is just kind of a brain dump. I don't have any concrete plan for tackling these right now myself. For now I'll probably just keep hacking up what I need as I need it and wait to see if any patterns emerge :-). But I figured it was worth writing it down in case it sparks ideas for anyone else. And if anyone wants to collaborate I'm open to that too!

**Comment by webknjaz** [comment]
@njsmith nice! Especially I like the commit messages in the repo :)

BTW I've had another early app experiment FTR https://github.com/webknjaz/ansiwatch-bot/tree/master/ansiwatch_bot

Collaboration? Sounds cool. I think we'd be able to distill some reusable parts to have them in a shared lib...
I think I'll steal some of your API ideas back into octomachinery. Some of refactoring pending anyway, just haven't had time to get it done.

Oh! And loved your texts in notes and readme!

P.S. I've got even more thoughts about the router + got some more of Apps experience in terms of problems/unpleasant surprises... It'd be great to have some common strategies for dealing with those.

**Comment by brettcannon** [comment]
I don't know how GH Actions changes things as those are designed to be reusable since you can use them by simply referencing a repository.

**Comment by brettcannon** [comment]
This idea hasn't really gone anywhere in the past year since the last comment and two years since we opened the issue. I think GitHub Actions changes things enough that I think this isn't as important. As well, I think it would also make sense as a separate project while keeping this one at the API level.
