### ISSUE TITLE
"data" arg can be made optional in GitHubAPI.post

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#70]
It is possible to make a POST request to GitHub API without passing in any `data`.

Example: https://developer.github.com/v3/apps/#create-a-new-installation-token

Currently `data` is required in `GitHubAPI.post()`

It would be great it `data` can be made optional to handle this situation.

**Comment by Mariatta** [comment]
A workaround is to simply pass in `data=b""`.

**Comment by brettcannon** [comment]
I don't think I have ever seen a REST API where a POST actually had not body.

The requirement for `data` was on purpose in order to prevent people from forgetting it. I'm a little tempted to say we should document the `b""` solution in the rare case it shouldn't be specified, but I'm open to be convinced otherwise.

**Comment by Mariatta** [comment]
Documenting the `data=b""` workaround sounds good.
So far I found two POST endpoints that don't need any data:
[create new installation token](https://developer.github.com/v3/apps/#create-a-new-installation-token) and [create a GitHub app from manifest](https://developer.github.com/v3/apps/#create-a-github-app-from-a-manifest).

**Comment by webknjaz** [comment]
FTR, talking about REST, it's not a rare case: if the API "knows" the kind of object creation of which you want to request (from the URL) and the auth data is provided via headers, it's quite common to have no body.
